name: 'Codiga GitHub action'
description: 'Ensure your code quality meet given standards'
inputs:
  repo_token:
    description: 'Token to checkout the repository.'
    required: true
  codiga_api_token:
    description: 'API Token to access Codiga. Set to none if you use access and secret keys'
    required: true
    default: ''
  min_quality_grade:
    description: 'Minimum grade. Valid options are EXCELLENT, GOOD, NEUTRAL, WARNING, CRITICAL. Leave blank to ignore.'
    required: true
    default: ''
  min_quality_score:
    description: 'Minimum quality score from 0 (worst) to 100 (best)'
    required: true
    default: '0'
  max_defects_rate:
    description: 'Maximum defect rate per line of code (e.g. 0.01 for 1 defect per 100 lines of code). Leave 0 to ignore.'
    required: true
    default: '0'
  max_complex_functions_rate:
    description: 'Maximum number of complex functions rate (e.g. number of complex functions / number of functions). Leave 0 to ignore.'
    required: true
    default: '0'
  max_long_functions_rate:
    description: 'Maximum number of long functions rate (e.g. number of long functions / number of functions). Leave 0 to ignore.'
    required: true
    default: '0'
  project_name:
    description: 'Project on codiga. Will use the preferences of this analysis. Leave blank and no preferences are used'
    required: true
    default: ''
  max_timeout_sec:
    description: 'Timeout before giving up (in case analysis takes too long). Default is 10 minutes'
    required: true
    default: '600'
  force_ref:
    description: 'Force the GitHub action to analyze a given ref. Leave to none if you want to analyze branch being pushed (default)'
    required: true
    default: 'none'
branding:
  icon: 'search'  
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.min_quality_grade }}
    - ${{ inputs.min_quality_score }}
    - ${{ inputs.max_defects_rate }}
    - ${{ inputs.max_complex_functions_rate }}
    - ${{ inputs.max_long_functions_rate }}
    - ${{ inputs.project_name }}
    - ${{ inputs.max_timeout_sec }}
    - ${{ inputs.force_ref }}
