name: main-codiga

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: codiga
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v3.4.0
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "✅ Check"
        run: docker build -t codiga/github-action -f Dockerfile .
